#!/bin/bash

if [ -f env.txt ];then
    environment=`cat env.txt`
else
    echo "Please add your preferred virtualenv to env.txt"
    echo ">> echo \"envname\" > env.txt"
    exit 1

fi

echo $WORKON_HOME/$environment/bin/activate
source $WORKON_HOME/$environment/bin/activate

pushd tvdjango
python manage.py "$@"
popd

